config/routes.rb
Rails.application.routes.draw do
  root to: 'top_pages#top'
  get 'references', to: 'references#new'
  resources :users, only: %i[new create]
  resources :jellyfishes, only: %i[create index edit update show] do
    resource :like, only: %i[create]
  end

  resources :ranks, only: %i[index]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :jellyfishes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jellyfish.rb
class Jellyfish < ApplicationRecord
  mount_uploader :jellyfish_image, JellyfishImageUploader
  has_many :likes, dependent: :destroy
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :jellyfish
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true, length: { maximum: 255 }

  enum role: { general: 0, admin: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :success, :info, :warning, :danger
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new(comment_params)
  end

  def destroy
    @comment.destroy!
  end
    
  private
    
  def comment_params
    params.require(:comment).permit(:body).merge(jellyfish_id: params[:jellyfish_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @jellyfish = Jellyfish.find(params[:jellyfish_id])
    @alreadylike = Like.find_by(ip: request.remote_ip, jellyfish_id: params[:jellyfish_id])
    if @alreadylike
        redirect_back(fallback_location: root_path)
        flash[:notice] = "すでに投票しています、ありがとうございます！"
     else
        @like = Like.create(jellyfish_id: params[:jellyfish_id], ip: request.remote_ip)
        redirect_back fallback_location: root_path, success: '投票ありがとうございます！'
    end
  end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  def index
    @jellyfish_like_ranks = Jellyfish.find(Like.group(:jellyfish_id).order('count(jellyfish_id) desc').pluck(:jellyfish_id))
    @jellyfishes = Jellyfish.order("created_at DESC")
  end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
    def new; end
end

app/controllers/top_pages_controller.rb
class TopPagesController < ApplicationController
    def top; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
  @user = User.new
end

def create
  @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render :new
    end
end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/jellyfishes_helper.rb
module JellyfishesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/rank_helper.rb
module RankHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/layouts/admin_login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><%= "ログイン" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'admin', media: 'all' %>
  </head>
  <body class="hold-transition login-page">
    <div>
      <%= render 'shared/flash_message' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <html>
  <head>
    <meta charset="utf-8">
    <meta lang='ja'>
    <meta name="robots" content="noindex, nofollow">
    <title><%="ダッシュボード"%></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'admin', media: 'all' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  </head>

  <body class="hold-transition sidebar-mini">
  <div class="wrapper">

    <%= render 'admin/shared/header' %>
    <%= render 'admin/shared/sidebar' %>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
     <%= render 'shared/flash_message' %>
     <%= yield %>
    </div>
    <!-- /.content-wrapper -->

    <%= render 'admin/shared/footer' %>

  </div>

  <%= javascript_include_tag 'admin' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_messages", class="alert alert-danger">
      <ul class="mb-0">
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom bg-dark text-center text-lg-start'>
    <div class="text-center p-4" style='background-color:#00bfff;'>
        <div class='copyright'>
          <%= link_to "参考文献", references_path, class: 'navbar-brand naver-light'  %>
          <p>Copyright © 2022. Jellyfish-Election</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
<nav class="navbar navbar-dark" style="background-color:#00bfff;">
  <%= link_to "クラゲ総選挙", root_path, class: 'navbar-brand'  %>
  <%= link_to "投票はこちら！", jellyfishes_path, class: 'navbar-brand naver-light'  %>
    <%= link_to "開票結果", ranks_path, class: 'navbar-brand naver-light'  %>
  </nav>
</header>