config/routes.rb
Rails.application.routes.draw do
  root to: 'top_pages#top'
  get 'references', to: 'references#new'
  resources :users, only: %i[new create]
  resources :jellyfishes, only: %i[create index edit update show] do
    resource :like, only: %i[create]
  end

  resources :ranks, only: %i[index]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :jellyfishes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jellyfish.rb
class Jellyfish < ApplicationRecord
  mount_uploader :jellyfish_image, JellyfishImageUploader
  has_many :likes, dependent: :destroy
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :jellyfish
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true, length: { maximum: 255 }

  enum role: { general: 0, admin: 1 }
end

app/controllers/admin/jellyfishes_controller.rb
class Admin::JellyfishesController < Admin::BaseController
   before_action :set_jellyfish, only: %i[show edit update destroy]
   def new
    @jellyfish = Jellyfish.new
   end
   
   def index
     @jellyfishes = Jellyfish.all
   end

   def show ;end

   def edit ;end

   def update
     @jellyfish.update(jellyfish_params)
     redirect_to admin_jellyfish_path
   end

   def destroy
     @jellyfish.destroy!
     redirect_to admin_jellyfish_path
   end
          
   private
      
   def set_jellyfish 
     @jellyfish = Jellyfish.find(params[:id])
   end

   def jellyfish_params
     params.require(:jellyfish).permit(:title, :body, :jellyfish_image, :jellyfish_image_cache)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :success, :info, :warning, :danger
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new(comment_params)
  end

  def destroy
    @comment.destroy!
  end
    
  private
    
  def comment_params
    params.require(:comment).permit(:body).merge(jellyfish_id: params[:jellyfish_id])
  end
end

app/controllers/jellyfishes_controller.rb
class JellyfishesController < ApplicationController
  before_action :set_jellyfish, only: %i[show edit update destroy]

  def index
    @jellyfishes = Jellyfish.all
  end

  def new
    @jellyfish = Jellyfish.new
  end

  def create
    @jellyfish = Jellyfish.new(jellyfish_params)
    if @jellyfish.save
       redirect_to jellyfishes_path, success: "成功しました"
    else
       flash.now['danger'] = "失敗しました"
       render :new
    end
  end
    
  def show ;end

  def edit ;end
    
  def update
    @jellyfish.update(jellyfish_params)
    redirect_to jellyfish
  end

  def destroy
    @jellyfish.destroy!
    redirect_to jellyfish_path
  end
    
  private

  def set_jellyfish 
    @jellyfish = Jellyfish.find(params[:id])
  end

  def jellyfish_params
    params.require(:jellyfish).permit(:title, :body, :jellyfish_image, :jellyfish_image_cache)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @jellyfish = Jellyfish.find(params[:jellyfish_id])
    @alreadylike = Like.find_by(ip: request.remote_ip, jellyfish_id: params[:jellyfish_id])
    if @alreadylike
        redirect_back(fallback_location: root_path)
        flash[:notice] = "すでに投票しています、ありがとうございます！"
     else
        @like = Like.create(jellyfish_id: params[:jellyfish_id], ip: request.remote_ip)
        redirect_back fallback_location: root_path, success: '投票ありがとうございます！'
    end
  end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  def index
    @jellyfish_like_ranks = Jellyfish.find(Like.group(:jellyfish_id).order('count(jellyfish_id) desc').pluck(:jellyfish_id))
    @jellyfishes = Jellyfish.order("created_at DESC")
  end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
    def new; end
end

app/controllers/top_pages_controller.rb
class TopPagesController < ApplicationController
    def top; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to  jellyfishes_path
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
  @user = User.new
end

def create
  @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render :new
    end
end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/jellyfishes_helper.rb
module Admin::JellyfishesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/jellyfishes_helper.rb
module JellyfishesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/rank_helper.rb
module RankHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/jellyfishes/_jellyfish.html.erb
<tr>
  <td>
    <%= jellyfish.id %>
  </td>
  <td>
      <%= link_to jellyfish.title, admin_jellyfish_path(jellyfish) %>
  </td>
  <td>
    <%= l jellyfish.created_at, format: :long %>
  </td>
  <td>
    <%= link_to '詳細', admin_jellyfish_path(jellyfish), class: 'btn btn-info' %>
    <%= link_to '編集', edit_admin_jellyfish_path(jellyfish), class: 'btn btn-success' %>
    <%= link_to '削除', admin_jellyfish_path(jellyfish), method: :delete, data: { confirm: "削除しますか"}, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/jellyfishes/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= "編集" %></h1>
      <%= form_with model: @jellyfish, url: admin_jellyfish_path(@jellyfish), local: true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, class: 'form-control', rows: 10 %>
        </div>
        <div class="form-group">
          <%= f.label :jellyfish_image %>
          <%= f.file_field :jellyfish_image, onchange: 'previewFileWithId(preview)', class: 'form-control', accept: 'image/*' %>
          <%= f.hidden_field :jellyfish_image_cache %>
        </div>
        <div class='mt-3 mb-3'>
          <%= image_tag @jellyfish.jellyfish_image.url,
                        id: 'preview',
                        size: '300✖️200' %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/jellyfishes/index.html.erb
<div class="container mb-5 pt-2">
  <h1><%= "クラゲ一覧" %></h1>
    <%= link_to '新規', new_admin_jellyfish_path(@jellyfish), class: 'btn btn-light' %>
    <div class="row">
      <div class="col-md-12 mb-3">
      </div>
    </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= "ID" %></th>
          <th scope="col"><%= "タイトル"%></th>
          <th scope="col"><%= "作成日時" %></th>
          <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
         <%= render @jellyfishes %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <!-- ページネーション -->
    </div>
  </div>
</div>

app/views/admin/jellyfishes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= "投稿" %></h1>
      <%= render 'jellyfishes/form', { jellyfishes: @jellyfish } %>
    </div>
  </div>
</div>

app/views/admin/jellyfishes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= "詳細" %></h1>
      <div class="text-right mb-3">
        <%= link_to '編集', edit_admin_jellyfish_path(@jellyfish), class: 'btn btn-success' %>
        <%= link_to '削除', admin_jellyfish_path(@jellyfish), method: :delete, data: { confirm: '削除しますか？'}, class: 'btn btn-danger' %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row"><%= "ID" %></th>
          <td><%= @jellyfish.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= "タイトル"  %></th>
          <td><%= @jellyfish.title %></td>
        </tr>
        <tr>
          <th scope="row"><%= "本文"%></th>
          <td><%=  @jellyfish.body %></td>
        </tr>
        <tr>
          <th scope="row"><%= '作成日時' %></th>
          <td><%= l @jellyfish.created_at, format: :long %></td>
        </tr>
      </table>
    </div>
  </div>
</div>